#!/usr/bin/env bash

run_ruby() {

    ruby_version="2.1.3"

    e_process "Installing Ruby $ruby_version ..."
    rvm install "$ruby_version"

    e_process "Setting $ruby_version as global default Ruby ..."
      rvm --default use 2.1.1

    e_process "Updating to latest Rubygems version ..."
      gem update --system

    e_process "Installing Bundler to install project-specific Ruby gems ..."
      gem install bundler --no-document --pre

    e_process "Configuring Bundler for faster, parallel gem installation ..."
      number_of_cores=$(sysctl -n hw.ncpu)
      bundle config --global jobs $((number_of_cores - 1))

    e_process "Installing Rake"
      gem install rake --no-document

    [[ $? ]] && e_success "Done"
}
